import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
import { cn } from '@/lib/utils';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="fixed top-0 left-0 right-0 p-4 flex justify-between items-center">
            <div className="flex items-center gap-4">
              <Link
                href="/"
                className={cn(
                  'text-lg font-medium hover:text-gray-600 transition-colors'
                )}
              >
                Home
              </Link>
              <Link
                href="/cool"
                className="text-lg font-medium hover:text-gray-600 transition-colors"
              >
                Cool
              </Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
